// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.RobotContainer;

/**
 *
 */
public class DriveSubsystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX leftMotorController;
private WPI_TalonSRX rightMotorController;
private DifferentialDrive tankDriveController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private NetworkTable limelightTable = NetworkTableInstance.getDefault().getTable("limelight-cybears");

    double turnkp = .0175;
    double turnki = 0.0;
    double turnkd = 0;
    private PIDController turnToTargetPID = new PIDController(turnkp, turnki, turnkd); 
    private double turnPower = 0.0;

    double drivekp = .3;
    double driveki = 0;
    double drivekd = 0;
    private PIDController driveToTargetPID = new PIDController(drivekp, driveki, drivekd);
    private double drivePower = 0.0;

    
    /**
    *
    */
    public DriveSubsystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
leftMotorController = new WPI_TalonSRX(7);
 
 

rightMotorController = new WPI_TalonSRX(5);
 
 

tankDriveController = new DifferentialDrive(leftMotorController, rightMotorController);
 addChild("TankDriveController",tankDriveController);
 tankDriveController.setSafetyEnabled(false);
tankDriveController.setExpiration(0.1);
tankDriveController.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    rightMotorController.setInverted(true);
    turnToTargetPID.setTolerance(2);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        if (limelightTable.getEntry("tv").getDouble(0) == 1){
            turnPower = turnToTargetPID.calculate(limelightTable.getEntry("tx").
                getDouble(0),0);
            drivePower = driveToTargetPID.calculate(limelightTable.getEntry("ta").
                getDouble(0), 3.5);
            if (turnPower < 0) 
                turnPower = turnPower - 0.125;
            else 
                turnPower = turnPower + 0.125;
            if (turnToTargetPID.atSetpoint()) turnPower = 0;
            SmartDashboard.putNumber("PID Turn Power", turnPower);
            SmartDashboard.putNumber("PID Drive Power", drivePower);
        }

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void driveWithStick(){
        Joystick stick = RobotContainer.getInstance().getJoystick1();
        tankDriveController.arcadeDrive(stick.getY(), -stick.getZ(),false);
        //tankDriveController.arcadeDrive(stick.getY(), -stick.getZ(),true);
        //driveWithValues(0,0);
        SmartDashboard.putNumber("stickpower", stick.getZ());
    }

    public void driveWithValues(double y, double z){
        Joystick stick = RobotContainer.getInstance().getJoystick1();
        if (limelightTable.getEntry("tv").getDouble(0)==1){
            tankDriveController.arcadeDrive(stick.getY(), turnPower, false
            );
        SmartDashboard.putNumber("stickpower", turnPower);

        } else {
            driveWithStick();
        }

    }

    public void resetChasePIDs(){
        turnToTargetPID.reset();
        driveToTargetPID.reset();
    }

}

